version: "3.2"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${STATIC_FILES}:/var/www/html/
    container_name: php
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ${STATIC_FILES}:/usr/local/apache2/htdocs/
    container_name: apache
  db:
    image: mysql:${MYSQL_VERSION:-latest}
    command: --default-authentication-plugin=mysql_native_password
#    restart: always
    ports:
      - "9997:3306"
    volumes:
      - ${DB_PATH}/data:/var/lib/mysql
      - ${DB_PATH}/config:/etc/mysql/conf.d
      - ${DB_PATH}/sqlinit:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql
  adminer:
    image: adminer
#    restart: always
    ports:
    - 9996:8080
    networks:
      - backend   
    container_name: adminer    
networks:
  frontend:
  backend:
volumes:
    data:
